name: rhyme-with-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - ipykernel
  - python=3.7
  - pip:
    - imageio==2.6.1
    - pathtools==0.1.2
    - streamlit
    - jupyter-server-proxy
    - nbserverproxy
